name: Liferay FnKit
run-name: Releasing Liferay FnKit
on: 
  push:
    tags:        
      - '**'
jobs:
  Build-Fragment-Assets:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build CX assets
        run: ./build-client-extension-assets.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a release for ${{ github.ref }}
          draft: false
          prerelease: false
          owner: peterrichards-lr
          repo: liferay-fnkit-global-js
      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./assets/*"]'